# This is basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  create-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
         credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: Execute VM creation script
        run: |
          echo "running script"
          chmod 777 ./create_vm.sh
          sh create_vm.sh

# If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo "created VM Instance"
