name: Create VM on Dev Push

on:
  push:
    branches:
      - dev

jobs:
  create-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute VM creation script
        run: |
          cd assignment10
          sh create_vm.sh
